### DISCUSSION TITLE
StarCraft 2 cannot be launched with an error

### DISCUSSION THREAD

**Discussion by piquark6046** [bottlesdevs/Bottles#3835] [Q&A]
StarCraft 2 said the program cannot be launched because `DDRAW.dll` is missing.
However, it does already exist in `C:\Windows\System32`.

```yml
Arch: win64
CompatData: ''
Creation_Date: '2025-04-03 20:55:53.545291'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.6
Environment: Custom
Environment_Variables: {}
External_Programs:
    8b65da15-fece-4ffd-91a1-77c8b89a88fd:
        executable: Battle.net.exe
        folder: /home/piqua/.var/app/com.usebottles.bottles/data/bottles/bottles/BattleNet__121/drive_c/Program
            Files (x86)/Battle.net
        id: 8b65da15-fece-4ffd-91a1-77c8b89a88fd
        name: Battle.net
        path: /home/piqua/.var/app/com.usebottles.bottles/data/bottles/bottles/BattleNet__121/drive_c/Program
            Files (x86)/Battle.net/Battle.net.exe
Installed_Dependencies:
- cnc-ddraw
- cjkfonts
- d3dcompiler_47
- d3dx11
- vcredist2019
- webview2
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.9.0
Name: BattleNet
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: false
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mangohud_display_on_game_start: true
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: wine
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: BattleNet__121
Runner: ge-proton9-26
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2025-04-03 21:17:20.890835'
VKD3D: vkd3d-proton-2.14.1
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
```
