### ISSUE TITLE
[Request] Installers action to "blacklist" executable from the programs list

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1183]
**Is your feature request related to a problem? Please describe.**
Sometimes a program came with multiple entries which are not needed at all (at least in this context). As installers already install a new program entry, it should also be able to blacklist the wrong ones.

**Describe the solution you'd like**
Introduce a new action who takes care of this task, so giving it a list of executable paths to blacklist:
```yaml
action: blacklist
  executables: 
    - path/to_first.exe
    - path/to_second.exe
```
