### ISSUE TITLE
[Bug]: Parameters when depending on Installers don't resolve as expected.

### ISSUE THREAD

**Issue by sjenkins7** [bottlesdevs/Bottles#1400]
### Describe the bug

If you have an installer that uses dependant `installers` (e.g. Steam), if `Parameters` conflict - these do not resolve as expected.

In this specific example - Steam has DXVK enabled, which causes blackscreens in the app i'm building the installer for. As a result, in my installer, I have DXVK off.

I'd expect that the Parameters in the top level installer to take precedence & before any of the `Dependencies` are installed

What results is Bottles enabling the Parameters from the Steam installer, while glossing over the ones in the top-level installer. These parameters provided by Steam impact the `Dependencies`, which introduces instability. Bottles claims DXVK is disabled, but in reality this is not the case - the app Blackscreens on launch, consistent with DXVK still being on. Only if I toggle DXVK on and back off, does the setting take effect & the app work as expected. 

### To Reproduce

Attempt to use the following installer in a clean "Custom" bottle:

```
Name: 7th Heaven
Description: Modding platform for Final Fantasy 7
Arch: win64

Installers:
- [ steam ]

Dependencies:
- vcredist2019
- dotnet48
- d3dcompiler_43
- d3dcompiler_47

Parameters:
  dxvk: false
  sync: esync
  discrete_gpu: true
  
Executable:
  name: 7th Heaven
  icon: 7th.png
  file: 7th Heaven.exe
  path: Program Files (x86)/7th Heaven/7th Heaven.exe
  
Steps:
- action: install_exe
  file_name: 7thHeaven-v2.4.0.0_Release.exe
  url: https://github.com/tsunamods-codes/7th-Heaven/releases/download/2.4.0/7thHeaven-v2.4.0.0_Release.exe
  file_checksum: d7646ff9cd55e9506817d0cc51e0e51c
  arguments: /VERYSILENT
  ```

### Package

Flatpak from Flathub

### Distribution

Endeavour OS

### Health Check

```shell
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.5-arch1-1
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs:
    LOCAL_INSTALLERS: /home/simon/.var/app/com.usebottles.bottles/data/bottles-programs
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Trying to create an installer for 7th Heaven, which depends on the Steam installer. The Steam installer has DXVK, which triggers multiple issues in the app ( e.,g. blackscreens ), that I definitely need to avoid.

The app will launch automatically at the end of the silent install ( for now ).

The installer provided is extremely unstable, due to intermittent esync issues impacting dependencies. Once i understand what might be causing this, i'll raise it separately
