### ISSUE TITLE
What is the purpose of versioning (it seems broken)

### ISSUE THREAD

**Issue by TiBeN** [bottlesdevs/Bottles#1431]
This issue is between feedback and bug report i don't know...

I had hard time to understand what is the purpose of versioning and i'm confused. 

At first i hoped this could allow me to create some kind of snapshot of the entire bottle (wineprefix files and conf), which could allow me to revert back the wineprefix in a previous state if, for example, i install a new program which broke the bottle (lib files overrides, corrupted registry.. the usual windows stuff).

First time i test, it seems no changes are detected when i create a new state. If i revert back to a previous state, it does not change anything on the files in the bottle, installed programs etc. What's more, the manifest is always empty:

```
Additions: []
Changes: []
Removed: []
Update_Date: '2022-05-06 19:39:37.659611'
```

So i took care to read the documentation and now i'm confused as it seems, according to the example, that only dependencies installed through Bottles UI seems to be tracked. So i took a test by installing the dependency "andale32". A state has been created automatically but the manifest is empty again.

I then created manually another state because previous one seems to have been created "before" the installation of the dependency (as the name of the state suggests it: `before andale32`...). But again the manifest is completely empty.

i then took a look at the states yml files and directory inside the bottle directory out of curiosity, and they seems empty:

```
[ben@dellxps13 states]$ tree
.
├── 0
│   ├── drive_c
│   ├── files.yml
│   └── index.yml
├── 1
│   ├── drive_c
│   ├── files.yml
│   └── index.yml
├── 2
│   ├── drive_c
│   ├── files.yml
│   └── index.yml
├── index.yml
└── states.yml
```

```
[ben@dellxps13 states]$ cat states.yml 
States:
    '0':
        Comment: first run
        Creation_Date: '2022-05-06 19:39:14.115649'
    1:
        Comment: before andale32
        Creation_Date: '2022-05-06 19:39:37.660226'
    2:
        Comment: mcgee
        Creation_Date: '2022-05-06 19:50:47.726824'
Update_Date: '2022-05-06 19:50:47.726830'
```

```
[ben@dellxps13 states]$ cat index.yml 
Files: []
Update_Date: '2022-05-06 19:50:47.724892'
```

Simple cat of every yml files inside numbered folders:
```
[ben@dellxps13 states]$ cat **/*.yml
Files: []
Update_Date: '2022-05-06 19:39:14.112384'
Additions: []
Changes: []
Removed: []
Update_Date: '2022-05-06 19:39:14.112653'
Files: []
Update_Date: '2022-05-06 19:39:37.658831'
Additions: []
Changes: []
Removed: []
Update_Date: '2022-05-06 19:39:37.659611'
Files: []
Update_Date: '2022-05-06 19:50:47.724892'
Additions: []
Changes: []
Removed: []
Update_Date: '2022-05-06 19:50:47.725961'
```

Something seems broken here but more generally i don't really understand what to expect from this feature. Looks like this should at least deserve a more in depth explanation in the documentation.

**Comment by mirkobrombin** [comment]
Thanks for the report, a regression occurred and the tool was not checking files recursively, resulting in no changes.

First state (bottle initialized):
```yaml
Additions:
-   checksum: cb438388dcb07380e65b8ebf9c575207
    file: windows/system32/winedevice.exe
-   checksum: dc6039e47ce82c5729781790bd0dc94c
    file: windows/system32/drivers/mountmgr.sys
-   checksum: 499e21680bebcd31f70c20987b93d6f8
    file: windows/system32/drivers/cng.sys
-   checksum: e484ec102bbd0edf39171b19ba4d39c3
    file: windows/system32/drivers/dxgkrnl.sys
-   checksum: 84f8d593ae2430c6dd666af9941ae73f
    file: windows/system32/drivers/dxgmms1.sys
-   checksum: 3878b7ef488ebc91ec6c19f130908a30
    file: windows/system32/drivers/fltmgr.sys
-   checksum: 04510e275522ec1677a753052a6c4cff
    file: windows/system32/drivers/hidclass.sys
-   checksum: f0715ae7c59cf8ca8db65fa6900200cb
    file: windows/system32/drivers/hidparse.sys
-   checksum: 60b20a330fb1f883a5886e9c69a0fdc0
    file: windows/system32/drivers/http.sys
-   checksum: 006be6e6b2670279f96656de76155b1b
    file: windows/system32/drivers/ksecdd.sys
-   checksum: 7350f76d7833cf84f03b40fa294ad748
    file: windows/system32/drivers/ndis.sys
-   checksum: 4f8c7dab5cca64c6594c9c7ea6dc8473
    file: windows/system32/drivers/netio.sys
-   checksum: 6428ef133b6a3dbf152927f513c9d80b
    file: windows/system32/drivers/nsiproxy.sys
-   checksum: 5dd6f2c6b65a0ea6433550d4e5692484
    file: windows/system32/drivers/scsiport.sys
-   checksum: 41c9eb9f707d78fe96fb5b67b241eccd
    file: windows/system32/drivers/tdi.sys
-   checksum: 97cfaf240ec6d7005a53c0cae21bde80
    file: windows/system32/drivers/usbd.sys
-   checksum: 1877855dffac9c88ad771ac6566475e0
    file: windows/system32/drivers/winebus.sys
-   checksum: 2e0fcaf658b35708a4c19b7c8a91777a
    file: windows/system32/drivers/winehid.sys
-   checksum: 4564df9db1484a286096aa74d2e62609
    file: windows/system32/drivers/wineusb.sys
-   checksum: 23067ee7b0102f639f5818292e48c36a
    file: windows/system32/drivers/winexinput.sys
-   checksum: 731b35ca0fcece06bc19f379a6864d8f
    file: windows/system32/drivers/etc/hosts
-   checksum: 28d5c5cee9fd3017097682b2eb924648
    file: windows/system32/drivers/etc/networks
-   checksum: b03a9753491fe3bdfb1f6a79b72fa1e3
    file: windows/system32/drivers/etc/protocol
-   checksum: 4330189fdce25005dcc8e70f11f729d7
    file: windows/system32/drivers/etc/services
-   checksum: 2dd54ce0e8769bd956a2e292ac4c64bf
    file: windows/system32/drivers/sharedgpures.sys
-   checksum: 87a5b13f1da1a601de043589a29c64b4
    file: windows/system32/catroot/{f750e6c3-38ee-11d1-85e5-00c04fc295ee}/msxmlx.cat
-   checksum: 0cff0641bee825ed3ad0cf05f80222b8
    file: windows/system32/spool/drivers/x64/3/wineps.drv
-   checksum: 3947129e0967089c736f91a2989d89d8
    file: windows/system32/spool/drivers/color/srgb color space profile.icm
-   checksum: 647711c7895be447d87b6f5221397bc3
    file: windows/system32/spool/drivers/win40/0/wineps16.drv
-   checksum: 78e6c6c590e83405ca815d7af737d835
    file: windows/system32/spool/drivers/w32x86/3/wineps.drv
-   checksum: 5ccaa328a1d9ef6f58d0591519f014b1
    file: windows/system32/explorer.exe
-   checksum: 00ca727499546f30a157c4fb6a75444c
    file: windows/system32/iexplore.exe
-   checksum: 42cb1b41a0f10878ab33039e39224077
    file: windows/system32/notepad.exe
-   checksum: c47a1c73078ecc70d0810371413bf144
    file: windows/system32/win32k.sys
-   checksum: 527cc43b258e599d6654e5bfd61d2e8d
    file: windows/system32/msxml.dll
-   checksum: 48171a864ecb6577b3a14ac2637c2d0a
    file: windows/system32/msxml2.dll
-   checksum: dfadb4c6435934678b3e4795eb74c96d
    file: windows/system32/msxml3.dll
-   checksum: 7ba802dec36a8f3c1c261d3d5e7c679e
    file: windows/system32/msxml4.dll
-   checksum: 4035e082f4f063cefd0c17a96d78e72c
    file: windows/system32/msxml6.dll
-   checksum: f8d8bb1666f8d04287351a9176b9fdde
    file: windows/system32/shdocvw.dll
-   checksum: 01d06435e9b40fcb15254c023197b547
    file: windows/system32/gecko/plugin/npmshtml.dll
-   checksum: 2df882a5f54dc5180f227a04f69dc8be
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/blocklist.xml
-   checksum: f9b700918938fec0a3730ce8d29d01b3
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/chrome.manifest
-   checksum: e99b1d269896bdc276553e57307ee459
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/components/browsercomps.dll
-   checksum: a81e655e381a16a79c5bc34893bf6014
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/components/components.manifest
-   checksum: 59d6d2066e5a76788d5d8f1e7c845da5
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
-   checksum: 11d1fdb1737cfe729841e635cded167e
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/features/e10srollout@mozilla.org.xpi
-   checksum: 97c732797447ef16641f6fdcaa508aaa
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/features/firefox@getpocket.com.xpi
-   checksum: 6b1ff9a2600d326e6f49d8f0dd2f5e36
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/features/loop@mozilla.org.xpi
-   checksum: 2667fc8558d167d66d6eeb6827b5400a
    file: windows/system32/gecko/2.47.2/wine_gecko/browser/omni.ja
-   checksum: 5857e71a7a522f5bda99465d6545bb03
    file: windows/system32/gecko/2.47.2/wine_gecko/defaults/pref/channel-prefs.js
-   checksum: 9e434916d1d56447f89fb820841e3f11
    file: windows/system32/gecko/2.47.2/wine_gecko/dependentlibs.list
-   checksum: de7d2fb2a926fd13f49b784f9272cd65
    file: windows/system32/gecko/2.47.2/wine_gecko/dictionaries/en-US.aff
-   checksum: 7ccd1981e935a545668ee384e4c7256d
    file: windows/system32/gecko/2.47.2/wine_gecko/dictionaries/en-US.dic
-   checksum: 76d01d866412f6cf83244fb5525321ce
    file: windows/system32/gecko/2.47.2/wine_gecko/freebl3.dll
-   checksum: 26998d686d0710ff00a746a6787d29fc
    file: windows/system32/gecko/2.47.2/wine_gecko/gmp-clearkey/0.1/clearkey.dll
-   checksum: 6480e7404342bd4f59a5820e18e9b2c6
    file: windows/system32/gecko/2.47.2/wine_gecko/gmp-clearkey/0.1/clearkey.info
-   checksum: 983502ebddb15c5297ac350727e541a8
    file: windows/system32/gecko/2.47.2/wine_gecko/lgpllibs.dll
-   checksum: 81a7296ab4ffc5419ff857dffb1972ca
    file: windows/system32/gecko/2.47.2/wine_gecko/libEGL.dll
-   checksum: 99e386029d908a1afdbfa46e7952fc7a
    file: windows/system32/gecko/2.47.2/wine_gecko/libGLESv2.dll
-   checksum: ccdeb3d9d4d89c8b81b4f48386cd0e17
    file: windows/system32/gecko/2.47.2/wine_gecko/mozavcodec.dll
-   checksum: 1712b104eb1db3ed75df7248bd977568
    file: windows/system32/gecko/2.47.2/wine_gecko/mozavutil.dll
-   checksum: 4c81c2651c58e60afeaa03b36a1bc7d2
    file: windows/system32/gecko/2.47.2/wine_gecko/mozglue.dll
-   checksum: 9628ad5d0650e96e4c620096d4c9b8c3
    file: windows/system32/gecko/2.47.2/wine_gecko/nss3.dll
-   checksum: 19d576839c6eb1e30a5bd51da9593fba
    file: windows/system32/gecko/2.47.2/wine_gecko/nssckbi.dll
-   checksum: 3805d2674fb78049895a54842b958705
    file: windows/system32/gecko/2.47.2/wine_gecko/nssdbm3.dll
-   checksum: b1b96bfa8ae40f30bfefa2c87f612de2
    file: windows/system32/gecko/2.47.2/wine_gecko/omni.ja
-   checksum: c5b50e8b138aee5fa26904d8f2d759fa
    file: windows/system32/gecko/2.47.2/wine_gecko/plugin-container.exe
-   checksum: 4c65acb611c5d0507c327fbab758267f
    file: windows/system32/gecko/2.47.2/wine_gecko/softokn3.dll
-   checksum: fceb4a0dda4994d564f54a28ac0a891e
    file: windows/system32/gecko/2.47.2/wine_gecko/VERSION
-   checksum: 60f0da21d1bcbcdab965b9818c07d7b0
    file: windows/system32/gecko/2.47.2/wine_gecko/xul.dll
-   checksum: 35ceaeb4dc522a4683fb559a7bd577b6
    file: windows/system32/Speech/Common/sapi.dll
-   checksum: d80cfb932a1fff0c81fda486714e8bd3
    file: windows/system32/wbem/mofcomp.exe
-   checksum: 99d7e24f78643da298a1a4cf937a6b6f
    file: windows/system32/wbem/wbemdisp.dll
-   checksum: bb8863c391e4e6a229966c28989a73fa
    file: windows/system32/wbem/wbemprox.dll
-   checksum: 4f427daaea9aec9ac4947f766fb0d132
    file: windows/system32/wbem/wmic.exe
-   checksum: 18cc1991d170d6f854d1172aa85b0e45
    file: windows/system32/wbem/wmiutils.dll
-   checksum: d3cc802ed451060d68feb114914fce1b
    file: windows/system32/WindowsPowerShell/v1.0/powershell.exe
-   checksum: b72b3ee00472668fee8744442d40d0fd
    file: windows/system32/acledit.dll
-   checksum: 34fe292cc4e80311179a8d20f7afe7cc
    file: windows/system32/aclui.dll
-   checksum: ef2c9c9000a867547a916aa536c863da
    file: windows/system32/activeds.dll
-   checksum: 83b8e494b354b1b1fc0904e1d9245a89
    file: windows/system32/activeds.tlb
-   checksum: 27dd99425f9a7f8837793764a35c3e0f
    file: windows/system32/actxprxy.dll
-   checksum: 24817715ae7cf6dcfbb09dbb6dd41867
    file: windows/system32/adsldp.dll
-   checksum: cdb8a7ec510fde38efbee87ebea0b4f0
    file: windows/system32/adsldpc.dll
-   checksum: 43fa347fcb2069da54e811841e9a23a8
    file: windows/system32/advapi32.dll
-   checksum: 5fc524c2e4a7838339c8c3bfa415324d
    file: windows/system32/advpack.dll
-   checksum: a82379a9be9fb319caec4d101dabbfc7
    file: windows/system32/amsi.dll
-   checksum: d8b6111a9183ef43a68720b538053611
    file: windows/system32/amstream.dll
-   checksum: ebbfc473248ed689688802d7c6f4cd15
    file: windows/system32/apisetschema.dll
-   checksum: 49f19364a3812bb27454ca51b8a59ea8
    file: windows/system32/apphelp.dll
-   checksum: 47e8c719ed8e7bdc8cf3824f11afb561
    file: windows/system32/appwiz.cpl
-   checksum: 98ec8f52c53fef401fc26635d8bf00aa
    file: windows/system32/arp.exe
-   checksum: 3c3bfdde23433f331f18b991238a1537
    file: windows/system32/atl.dll
-   checksum: 022195d9e39ff03b1ef965da70487508
    file: windows/system32/atl100.dll
-   checksum: be74f5f1ef5a162383314a3c214a39fe
    file: windows/system32/atl110.dll
-   checksum: 31b3caa2e951a6113f254cbe0be900e0
    file: windows/system32/atl80.dll
-   checksum: 855aa64a311673efbf8e6e1031f848f1
    file: windows/system32/atl90.dll
-   checksum: 50b6a2c361d3e29d67ffa0bbb0640073
    file: windows/system32/atlthunk.dll
-   checksum: d018e9b2087594fc1f4926c7857515d6
    file: windows/system32/atmlib.dll
-   checksum: b20f7d1ab3b494ab37c3a2befd886cef
    file: windows/system32/attrib.exe
-   checksum: 9181ad13340eb4dd206a76b2e5362b51
    file: windows/system32/authz.dll
-   checksum: 5a53119886b3217523e82b9342f6c7f9
    file: windows/system32/avicap32.dll
-   checksum: ee2282e1fe1d997eed6be33ad680795b
    file: windows/system32/avifil32.dll
-   checksum: ad88580d18089453e48c31ec7a413fbb
    file: windows/system32/avrt.dll
-   checksum: 572b6b00f9880c4a1dc7554a46322a85
    file: windows/system32/bcrypt.dll
-   checksum: 2c1c32677262cfdf668348148985767f
    file: windows/system32/bluetoothapis.dll
-   checksum: 751370513375b5dc619ce6a373609dc1
    file: windows/system32/browseui.dll
-   checksum: 74f5831f46f0f83fbe681629ef1d06f9
    file: windows/system32/bthprops.cpl
-   checksum: 688044de6616b360b371b4abdc11967a
    file: windows/system32/cabarc.exe
-   checksum: bf1ff5ea92e760ba5a333453d0fbd33c
    file: windows/system32/cabinet.dll
-   checksum: f0b70184a33a2cac918099c259db8922
    file: windows/system32/cacls.exe
-   checksum: 71e188059ad4ad95204818e19d5e0f2e
    file: windows/system32/cards.dll
-   checksum: def5a079496b93b7ab8d084031ea54f2
    file: windows/system32/cdosys.dll
-   checksum: dd86929881e85ae6fd608655c89605be
    file: windows/system32/cfgmgr32.dll
-   checksum: 658dec5f299a8a884af9a8068728eb9d
    file: windows/system32/chcp.com
-   checksum: 04f89c63741d1497fc8c2a0cd0df6cd5
    file: windows/system32/clock.exe
-   checksum: e5508e7b5da2cc63502162bc89f46e7e
    file: windows/system32/clusapi.dll
-   checksum: 48500e951b652696ef83482643dbdecc
    file: windows/system32/cmd.exe
-   checksum: 9e7538f183b717c243693ab2144114c1
    file: windows/system32/combase.dll
-   checksum: 779df846a51de2cada60e0c73b1725fc
    file: windows/system32/comcat.dll
-   checksum: 4de7371b26a2cc48792a21e13910d633
    file: windows/system32/comctl32.dll
-   checksum: ca2b5c12b327d310bb3bbbc02e2f0b95
    file: windows/system32/comdlg32.dll
-   checksum: c03a4a76cbb39b0c5f4f31354f852211
    file: windows/system32/compstui.dll
-   checksum: 9372cd804ad3afe957d323588b060cd2
    file: windows/system32/comsvcs.dll
-   checksum: 7d190cb5251a0071a0cd4578847769eb
    file: windows/system32/concrt140.dll
-   checksum: 71fd3be4a18a23ae3e724dd9e32b18ca
    file: windows/system32/conhost.exe
-   checksum: 49df0badd69503839ede7dad8cf3dde2
    file: windows/system32/connect.dll
-   checksum: b8f95aaff295d4e11e77f1e4d4d1e817
    file: windows/system32/control.exe
-   checksum: 5fec28612e8d24cc4b72bd977757a850
    file: windows/system32/credui.dll
-   checksum: fa49650cbf6d7411e2a1f15268b4cd34
    file: windows/system32/crtdll.dll
-   checksum: e25c5520a25747634aa5d55be41a78c5
    file: windows/system32/crypt32.dll
-   checksum: fa17be3353eea41ba9416734ba7fb90c
    file: windows/system32/cryptdlg.dll
-   checksum: 5f1895f79a7930940b654c6fb3dc840b
    file: windows/system32/cryptdll.dll
-   checksum: e20b2cef9b19f456ecb1425822c6f53d
    file: windows/system32/cryptext.dll
-   checksum: 30ff1c71900cc6cffd05a6e89201e3c3
    file: windows/system32/cryptnet.dll
-   checksum: 5145022b40b5cee4c9dc85dd4f9b9f58
    file: windows/system32/cryptsp.dll
-   checksum: 6abc05501a7d01170435a181ffee4bc3
    file: windows/system32/cryptui.dll
-   checksum: 3134943a68886bd0830b2df344d48e8e
    file: windows/system32/cscript.exe
-   checksum: 5a568a45e5719af8932610aba8e55b67
    file: windows/system32/ctapi32.dll
-   checksum: 8c269e358df15e0769c12af41537c13f
    file: windows/system32/ctl3d32.dll
-   checksum: 82faa395e9e97ee51e0046688d45ed68
    file: windows/system32/d2d1.dll
-   checksum: fcb722d86b3eebf743161385633ba659
    file: windows/system32/d3d10.dll
-   checksum: c95063596737426532f03589821b2f09
    file: windows/system32/d3d10core.dll
-   checksum: d5a4db0aaf42612e5a4234aa5f132766
    file: windows/system32/d3d10_1.dll
-   checksum: 3667edd466a55f3a85e779e5cfaa64b6
    file: windows/system32/d3d11.dll
-   checksum: 48942a6590aecf235ed41d30895ec4f4
    file: windows/system32/d3d12.dll
-   checksum: c7dd01dcbcb4176c196c4d9f0fb0fa1f
    file: windows/system32/d3d8.dll
-   checksum: c2d62a221da267686aeadc124dcf3217
    file: windows/system32/d3d8thk.dll
-   checksum: f91f6507a96a1c505b12ae3acb4c5697
    file: windows/system32/d3d9.dll
-   checksum: 2581199111bdbf66add56c1ae7890f92
    file: windows/system32/d3dcompiler_33.dll
-   checksum: 79f9db80217f96fb2363525a67ffe3ab
    file: windows/system32/d3dcompiler_34.dll
-   checksum: 72cbb2681f9f106401f5413f1e2a5ab0
    file: windows/system32/d3dcompiler_35.dll
-   checksum: 07f27a9acdd8c91a176f89081bc03cb1
    file: windows/system32/d3dcompiler_36.dll
-   checksum: e3c5c101b6520ebe1bf9fc0d16c7eb92
    file: windows/system32/d3dcompiler_37.dll
-   checksum: c370517815fdebb9c2036fc1d518a6c8
    file: windows/system32/d3dcompiler_38.dll
-   checksum: ecbc005767f4a71e245905a16c35f247
    file: windows/system32/d3dcompiler_39.dll
-   checksum: 5e0b082eb57c693c5caf5833e86e77e6
    file: windows/system32/d3dcompiler_40.dll
-   checksum: 7bea00a54c9e2b17f1a29639aeee8bab
    file: windows/system32/d3dcompiler_41.dll
-   checksum: 2931c58b43b16ac37178179807022c50
    file: windows/system32/d3dcompiler_42.dll
-   checksum: a72c7e068d90d213451e12f83866cdcc
    file: windows/system32/d3dcompiler_43.dll
-   checksum: 6e0baf9729b4daba817dc4e01d8c60ae
    file: windows/system32/d3dcompiler_46.dll
-   checksum: fdf37839a65d8f90c85b34d8cda2892c
    file: windows/system32/d3dcompiler_47.dll
-   checksum: 1e1054ccf352efabf9f9b9fdd5775620
    file: windows/system32/d3dim.dll
-   checksum: 5781ae447f20e4e39092cc8697e7b3bd
    file: windows/system32/d3dim700.dll
-   checksum: 1acb1536d855a78a677ff603707e1fa9
    file: windows/system32/d3drm.dll
-   checksum: 97926a9ca11cb31ba3055658cd5bc8ee
    file: windows/system32/d3dx10_33.dll
-   checksum: a516d3ab3bdd27d5fcbe3deb3be799e3
    file: windows/system32/d3dx10_34.dll
-   checksum: b192ea839741ec6d86be9af8e7612f0f
    file: windows/system32/d3dx10_35.dll
-   checksum: e5661919a810fd316b09b236bfa7d517
    file: windows/system32/d3dx10_36.dll
-   checksum: 634e1451d8d4fb8bdc53c3beda3b4b16
    file: windows/system32/d3dx10_37.dll
-   checksum: c16e6be0998c100289d48eff1cf1ae02
    file: windows/system32/d3dx10_38.dll
-   checksum: 8a3758aaaba79de4cc2e4e8093d3a2cc
    file: windows/system32/d3dx10_39.dll
-   checksum: 92f43f54e0005431a7853812a4565890
    file: windows/system32/d3dx10_40.dll
-   checksum: e4e5209252bca9c39f4bd7b79108ac6a
    file: windows/system32/d3dx10_41.dll
-   checksum: 5389670bb8a7fb84e30ff183208b1662
    file: windows/system32/d3dx10_42.dll
-   checksum: 14a22f51238c7c687cfa7ce72e603cfa
    file: windows/system32/d3dx10_43.dll
-   checksum: b216c38b73d58ffce802f589f520d003
    file: windows/system32/d3dx11_42.dll
-   checksum: 959ed118c4fb3934c112563f81a0bc35
    file: windows/system32/d3dx11_43.dll
-   checksum: 4c68a99332453fda4b3c9bdaae28f051
    file: windows/system32/d3dx9_24.dll
-   checksum: 7462b4b70bb03cb15dca223e2c48d8b7
    file: windows/system32/d3dx9_25.dll
-   checksum: 826fca76c4994492b292b065e3c0da9b
    file: windows/system32/d3dx9_26.dll
-   checksum: e73f2d729fa64ec4cd085b4c63ac7c7c
    file: windows/system32/d3dx9_27.dll
-   checksum: 88269c1ce8c2a09953ed53302f8184b6
    file: windows/system32/d3dx9_28.dll
-   checksum: 6c58ce224c5c3e00ae21c522d483659b
    file: windows/system32/d3dx9_29.dll
-   checksum: 12aeac6f7bf134b56d2e10daedf8dfae
    file: windows/system32/d3dx9_30.dll
-   checksum: a4eb83d72cdabf84647c483c26e0ce26
    file: windows/system32/d3dx9_31.dll
-   checksum: 5d47dc3709342dcb9d2029714a6ee070
    file: windows/system32/d3dx9_32.dll
-   checksum: beda4f063c9c8b3429684c677a5236d9
    file: windows/system32/d3dx9_33.dll
-   checksum: e340b3e81a7ef3189a4d56d8b636a466
    file: windows/system32/d3dx9_34.dll
-   checksum: 7d8125f3b08abfe70d12f2e62a4222f1
    file: windows/system32/d3dx9_35.dll
-   checksum: fc86878cb35c2bb9f065abe5605a5dfa
    file: windows/system32/d3dx9_36.dll
-   checksum: 926eab2c5036d4a19371685df25a87eb
    file: windows/system32/d3dx9_37.dll
-   checksum: ecda24a1cc7eaac0796c6e6ec89cc5e2
    file: windows/system32/d3dx9_38.dll
-   checksum: fdccb1e0ee1a4c060d53673b4ff428f5
    file: windows/system32/d3dx9_39.dll
-   checksum: 9f16cf96a317a2bad1075963df652147
    file: windows/system32/d3dx9_40.dll
-   checksum: b095e8d4c482a595c2405302365e2d6f
    file: windows/system32/d3dx9_41.dll
-   checksum: f312188b664d997c182a0eb939c90417
    file: windows/system32/d3dx9_42.dll
-   checksum: ad76f454980c701b336857479f49aba1
    file: windows/system32/d3dx9_43.dll
-   checksum: 99c3204ad8256db7bbb6e8b3ba7efe1f
    file: windows/system32/d3dxof.dll
-   checksum: b52d426caf51ad8e48e41b4f63fd830b
    file: windows/system32/davclnt.dll
-   checksum: 008ebf357d721d2947eeda70604a5fc4
    file: windows/system32/dbgeng.dll
-   checksum: 9735aa1c9ace8d24fa6501d7113a56f7
    file: windows/system32/dbghelp.dll
-   checksum: 05ecd4dc2cf0be3ac8125ee2a413a52b
    file: windows/system32/dciman32.dll
-   checksum: cfda4e4efc22188a48a3b41e762650bc
    file: windows/system32/dcomp.dll
-   checksum: 0775e3f662ee4e79733f7c0fa8ba82d5
    file: windows/system32/ddraw.dll
-   checksum: e34429ba287b2f56a005a6f4fb6c88d6
    file: windows/system32/ddrawex.dll
-   checksum: c038e522675f7752efcf4385a598b20a
    file: windows/system32/devenum.dll
-   checksum: 2a2b7813e721a18cf09eff93dcb11289
    file: windows/system32/dhcpcsvc.dll
-   checksum: df31ed09a83709246894f58a461f0949
    file: windows/system32/dhcpcsvc6.dll
-   checksum: 68f3ad40075e854d63700941875a196c
    file: windows/system32/dhtmled.ocx
-   checksum: 96858c38669921a4ae0c4b81e7a4df19
    file: windows/system32/difxapi.dll
-   checksum: f960e4809e99b643152905174c93c618
    file: windows/system32/dinput.dll
-   checksum: d72b0a656404cb9f8d13ac94c25f4d67
    file: windows/system32/dinput8.dll
-   checksum: b8ce6cb522b35a390155b3fbd52b40fa
    file: windows/system32/directmanipulation.dll
-   checksum: c6f8c3f195b42e60f99cc47ad6be85ad
    file: windows/system32/dism.exe
-   checksum: 1d525e2a5da10a8fb86636e8b29f972d
    file: windows/system32/dispex.dll
-   checksum: 95d940ccc014ebe05824884f9514abe6
    file: windows/system32/dllhost.exe
-   checksum: e403eedf894bf5fc5428eef4c9ce72ca
    file: windows/system32/dmband.dll
-   checksum: 774e01b6944ad271d04f5050d8254635
    file: windows/system32/dmcompos.dll
-   checksum: 8e4fb839303f08e6f1d3127455433b92
    file: windows/system32/dmime.dll
-   checksum: 1d983c58568ddd0f2c3d91e2642ec519
    file: windows/system32/dmloader.dll
-   checksum: 636c91fc6f8bb8fb645e5a657b35b5c9
    file: windows/system32/dmscript.dll
-   checksum: 0cb415d957e8bcd57877e18e307c7e73
    file: windows/system32/dmstyle.dll
-   checksum: fa65832152ff71a76a37d6805ba72932
    file: windows/system32/dmsynth.dll
-   checksum: 3d5c61c72a03cdcd5a3a4da04528fb17
    file: windows/system32/dmusic.dll
-   checksum: d20c5c3e760182c4781a5aee47d1d95b
    file: windows/system32/dmusic32.dll
-   checksum: b6a81e375fc42aa2985f0078b36e6b97
    file: windows/system32/dnsapi.dll
-   checksum: 3e6f04286d809c8710d6aa50f5f23192
    file: windows/system32/dplay.dll
-   checksum: b46438eb4763284b1a4b45467de643ff
    file: windows/system32/dplaysvr.exe
-   checksum: ae3751e0642a1723efeb61f2f9408d2f
# trimmed for better readability
Changes: []
Removed: []
Update_Date: '2022-05-07 10:51:55.864022'
```

Second state (after adding a new file):
```yaml
Additions:
-   checksum: d41d8cd98f00b204e9800998ecf8427e
    file: newfile.txt
Changes:
-   checksum: d41d8cd98f00b204e9800998ecf8427e
    file: newfile.txt
Removed: []
Update_Date: '2022-05-07 10:57:29.057146'
```

So restoring the first state, `newfile.txt` is removed:
![image](https://user-images.githubusercontent.com/9479903/167247310-fb43887c-1054-4329-9ebd-bdaf6f04b9f6.png)

With this in mind you can now read here: https://docs.usebottles.com/bottles/versioning

I'll distribute this fix soon.
