### ISSUE TITLE
Ensure program is installed before adding a new entry to programs list

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#1438]
follow-up: https://github.com/bottlesdevs/Bottles/issues/1401

## Problem
There is currently no trace for Windows executable errors, so Bottles continues to assume that everything is fine.

## Solution
Provide a "Checks" key to installers, so Bottles can check for registry keys and/or files to make sure the program was intalled.

```yaml
...
Checks:
    - reg_keys:
      - HKEY_LOCAL_MACHINE/key1
      - HKEY_LOCAL_MACHINE/key2
    - files:
      - path/to/file # starts from drive_c
      - path/to/another/file # only list a few files
```

`Checks` should be optional for back-compatibility.
