### ISSUE TITLE
[Bug]: Adding to library regression

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1684]
### Describe the bug

2022.6.28-brescia

In the previous release I made ticket https://github.com/bottlesdevs/Bottles/issues/1621 where I could finally add program to Library but not launch. It seems regression now. I cannot even add anymore even though Bottles says "<program> was added to your library"

```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/views/library.py", line 56, in update
    entry = LibraryEntry(self, u, e)
  File "/app/share/bottles/bottles/widgets/library.py", line 64, in __init__
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(entry['icon'], 24, 24)
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/home/mahmood/.var/app/com.usebottles.bottles/data/bottles/bottles/Guild-Wars-2/icons/Guild Wars 2.png” (3)
```

I tried adding multiple times and you can see in library.yml which also seems like another bug since they all have different ID. Bottles should stop user from adding if already added. When I go into Library it is blank!!!!!!!

```
91ac903d-5d61-4826-b771-583836d719fa:
  bottle:
    name: Guild Wars 2
    path: Guild-Wars-2
  icon: /home/mahmood/.var/app/com.usebottles.bottles/data/bottles/bottles/Guild-Wars-2/icons/Guild
    Wars 2.png
  id: Gw2-64.exe
  name: Guild Wars 2
101b06b8-89a8-4ecb-9f34-7f018050f485:
  bottle:
    name: Guild Wars 2
    path: Guild-Wars-2
  icon: /home/mahmood/.var/app/com.usebottles.bottles/data/bottles/bottles/Guild-Wars-2/icons/Guild
    Wars 2.png
  id: Gw2-64.exe
  name: Guild Wars 2
524e9cb3-c9a4-4176-975e-894c460e1460:
  bottle:
    name: Guild Wars 2
    path: Guild-Wars-2
  icon: /home/mahmood/.var/app/com.usebottles.bottles/data/bottles/bottles/Guild-Wars-2/icons/Guild
    Wars 2.png
  id: Gw2-64.exe
  name: Guild Wars 2
```

bottle.yml
```
Arch: win64
Creation_Date: '2022-02-13 12:03:35.316543'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.10.1
Environment: Gaming
Environment_Variables: {}
External_Programs:
    Gw2-64.exe:
        arguments: DXVK_ASYNC=1
        dxvk: true
        dxvk_nvapi: true
        executable: Gw2-64.exe
        folder: /home/mahmood/.var/app/com.usebottles.bottles/data/bottles/bottles/Guild-Wars-2/drive_c/Program
            Files/Guild Wars 2
        icon: com.usebottles.bottles-program
        id: Gw2-64.exe
        name: Guild Wars 2
        path: C:\Program Files\Guild Wars 2\Gw2-64.exe
        removed: null
        script: null
        vkd3d: true
Installed_Dependencies:
- d3dx9
- d3dcompiler_43
Language: sys
LatencyFleX: latencyflex-v0.1.0
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.4
Name: Guild Wars 2
Parameters:
    aco_compiler: true
    custom_dpi: 96
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: true
    environment_variables: ''
    fixme_logs: false
    fsr: true
    fsr_level: 2
    fullscreen_capture: false
    gamemode: true
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 60
    gamescope_fps_no_focus: 60
    gamescope_fullscreen: true
    gamescope_game_height: 1080
    gamescope_game_width: 1920
    gamescope_scaling: false
    gamescope_window_height: 480
    gamescope_window_width: 640
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: true
    renderer: gl
    sync: esync
    take_focus: true
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1024x768
    vkbasalt: false
    vkd3d: true
Path: Guild-Wars-2
Programs: {}
Runner: wine-ge-7-11
State: 0
Uninstallers:
    d3dcompiler_43: false
    d3dx9: false
Update_Date: '2022-06-27 17:34:41.322348'
VKD3D: vkd3d-proton-2.6
Versioning: false
Windows: win10
WorkingDir: ''

```

### To Reproduce

Open bottle in Terminal so you can see output
click 3 dots beside program
click Add to My Library

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
No issues
```

### Display Backend used by Bottles

X11
