### ISSUE TITLE
[Bug]: Unreadable glitching window

### ISSUE THREAD

**Issue by lgmarin** [bottlesdevs/Bottles#1687]
### Describe the bug

Running the program through the menu or inside the terminal display a glitched window, just like in the picture below.

![Screenshot_20220627_205327](https://user-images.githubusercontent.com/11378945/176058465-36fbfd43-3ca1-4e74-ae98-3904e115e1db.png)

### To Reproduce

1. Just run Bottles from the terminal or menu.

### Package

Flatpak from Flathub

### Distribution

Manjaro 

### Health Check

```yml
Version: 2022.6.28-brescia
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.18.6-1-MANJARO
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 8358649856
    Free: 8358506496
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.7GiB
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

Running on terminal produces no errors. Also, there is a list of all installed Flatpak packages.
![Screenshot_20220627_205816](https://user-images.githubusercontent.com/11378945/176059058-32f01ea1-b10c-451a-afdb-8c19f03cc081.png)
