### ISSUE TITLE
[Suggestion] Add install_exe zip download support

### ISSUE THREAD

**Issue by FricoRico** [bottlesdevs/Bottles#1800]
Some installers come wrapped inside a zip file. Currently the installer manifests only supports installing from an `msi` or `exe` file. It would be great if the manifest could download a zip file, unzip the file and then run the installer.

For my current manifest I'm trying to download and unzip the file using the `run_script` step into the Bottles `temp` folder so that the `install_exe` step uses the cached file. I haven't got this working yet and is not ideal.

**Comment by mirkobrombin** [comment]
A proposal would be miming the [`archive_extract`](https://maintainers.usebottles.com/dependencies/structure/Actions#title9) for dependencies, e.g.:

```yaml
- action: archive_extract
  file_name: archive_name.tar.xz
  rename: new_archive_name.tar.xz
  url: url/to/archive
  file_checksum: for_validation
  dest: path/to/destination  # supporting placeholders userdir/ drive/ bottle/ temp/. It should also make the folder if not exists
```
