### ISSUE TITLE
Indication for flatpak Mesa & VKD3D incompatible versions

### ISSUE THREAD

**Issue by martinmolin** [bottlesdevs/Bottles#1806]
### Problem
After installing Battle.net through the provided Installers, World of Warcraft could only run with DXVK and not VKD3D for DX12 when using an AMD GPU that use Mesa. Works with Nvidia in at least one case.

This can be a hard problem to solve if you are not aware that flatpak provide Mesa.

### Issue
The newer versions of VKD3D (selected by default by Bottles) requires a newer Mesa than provided by flatpak.

### Possible solution
Is it possible to perhaps indicate a version mismatch of Mesa & VKD3D or why it failed to use it when starting an application or somehow make the user aware that this could be the problem?

**Comment by TheEvilSkeleton** [comment]
Alternatively, we could make it build a newer version of Mesa. We could use LPub3D as a reference.

https://github.com/flathub/io.github.trevorsandy.LPub3D/blob/699e84aa4441989ef8fea31e35b9114879fd49c3/io.github.trevorsandy.LPub3D.json#L49-L67

@mirkobrombin what do you think?

**Comment by mirkobrombin** [comment]
> Alternatively, we could make it build a newer version of Mesa. We could use LPub3D as a reference.
> 
> https://github.com/flathub/io.github.trevorsandy.LPub3D/blob/699e84aa4441989ef8fea31e35b9114879fd49c3/io.github.trevorsandy.LPub3D.json#L49-L80
> 
> @mirkobrombin what do you think?

I agree with this

**Comment by TheEvilSkeleton** [comment]
Would something like this work?
```yaml
  - name: mesa
    buildsystem: meson
    config-opts:
      - '-Dosmesa=classic'
      - '-Ddri-drivers=[]'
      - '-Dgallium-drivers=[]'
      - '-Dvulkan-drivers=[]'
      - '-Dplatforms=[]'
    build-options:
      arch:
        aarch64:
          config-opts:
            - '-Dlibunwind=disabled'
    cleanup:
      - /share/drirc.d
      - /include
      - '*.a'
    sources:
      - type: archive
        url: https://archive.mesa3d.org/mesa-22.1.4.tar.xz
        sha256: 670d8cbe8b72902a45ea2da68a9da4dc4a5d99c5953a926177adbce1b1640b76
```

I'm unfamiliar with mesa.
