### ISSUE TITLE
[Bug]: Crashes when a bottle is not found

### ISSUE THREAD

**Issue by ju1ius** [bottlesdevs/Bottles#2456]
### Describe the bug

Bottles hangs forever on startup screen. When killed and reopened, the following exception trace is reported:

```
[Errno 2] Aucun fichier ou dossier de ce type: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Cemu_126/bottle.yml'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 63, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/frontend/windows/main_window.py", line 201, in get_manager
    mng = Manager(window=window, repo_fn_update=repo_fn_update)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 135, in __init__
    times.update(self.checks(install_latest=False, first_run=True))

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 192, in checks
    self.check_bottles()

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 778, in check_bottles
    process_bottle(b)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 735, in process_bottle
    self.update_config(

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 848, in update_config
    with open(os.path.join(bottle_path, "bottle.yml"), "w") as conf_file:
```

Notice that the bottle is named `Cemu 126` and it's bottle.yml is at `/home/USER/.var/app/com.usebottles.bottles/data/bottles/bottles/Cemu 126/bottle.yml`. Note the ` `(ascii  space) intead of `_` (underscore).

### To Reproduce

1. Open the app

### Package

Flatpak from Flathub

### Distribution

debian unstable

### Troubleshooting Logs

```shell
Since the appication hangs, no logs are available.
```

**Comment by Kinsteen** [comment]
Try to rename your folder to `Cemu_126`, it should fix the problem. I'm not sure what could have caused the bottle folder to create with a space, have you done something special to it? Like import it, duplicate it from somewhere else?

**Comment by ju1ius** [comment]
>  to rename your folder to Cemu_126, it should fix the problem.

Indeed, but since bottles created this folder in the first place, this issue might arise for other users.

> I'm not sure what could have caused the bottle folder to create with a space, have you done something special to it? Like import it, duplicate it from somewhere else?

Nope, it's been like this since forever and used to work without problem... 🤷🏻

**Comment by Kinsteen** [comment]
Which version are you using? Did you update recently? Was your bottle created on an older version? This shouldn't happen as normally when creating a bottle (in the last few versions) the spaces are replaced as `-`. It seems like this bottle was created a long time ago, and the retro compatibility fix is broken maybe

**Comment by ju1ius** [comment]
> Which version are you using? 

`2022.12.14.1` from flathub

> Did you update recently?

Yes as the version number shows.

> Was your bottle created on an older version?

Yes, Cemu 1.26 was released on 2021-12-24 so it was created around the same time (a year ago).

> It seems like this bottle was created a long time ago, and the retro compatibility fix is broken maybe.

That seems to be the case. At least it was working until recently.

**Comment by Kinsteen** [comment]
Yeah that makes sense. There was a change in this code in November, it should be the cause of the problem. I'm not sure if it's useful to fix this as it's a really small edge case and the fix is quite easy

**Comment by ju1ius** [comment]
As you like, but I don't see the point in replacing any character other than `/` in filesystem paths, unless you want to support Windows XP 🤣.

Anyway, as you said the fix is trivial so feel free to close.
Thanks.

**Comment by ju1ius** [comment]
Also, maybe the app shouldn't crash nor hang forever if a bottle is not found ?

**Comment by mirkobrombin** [comment]
I tried to replicate by making a bottle with a space on it and it is working as expected.

![image](https://user-images.githubusercontent.com/9479903/210842747-dcaa15e9-7e9d-4d0a-9c2b-8cc164ba8fd3.png)
![image](https://user-images.githubusercontent.com/9479903/210842802-bb3a28bc-24c1-46ef-99ee-d3928db5b43a.png)

```yaml
Arch: win64
Creation_Date: '2023-01-05 18:23:49.006879'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.0
Environment: Gaming
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.5.4
Name: boh test
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: esync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: boh-test
Runner: soda-7.0-8
Sandbox:
    share_net: true
    share_sound: true
State: 0
Uninstallers: {}
Update_Date: '2023-01-05 18:24:59.171156'
VKD3D: vkd3d-proton-2.7
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
run_in_terminal: false
session_arguments: ''
```
