### ISSUE TITLE
[Bug]: Flatpak bottle version 50.1 installation error 

### ISSUE THREAD

**Issue by mu-us61** [bottlesdevs/Bottles#2563]
### Describe the bug

I installed but infinite Almost done error happened so , I run bottle via console here is the output 
![Screenshot_2023-01-18_03-12-46](https://user-images.githubusercontent.com/73366454/213042213-3b3fe1cd-78c4-488d-b96c-0c1410cf7d9a.png)

### To Reproduce

just run bottle

### Package

Flatpak from Flathub

### Distribution

Debian 11

### Troubleshooting Logs

```shell
cant click almost done glitch doesnt allow me
```

**Comment by francescomasala** [comment]
Please can you try the following commands:
`dig mirror.usebottles.com`, `ping mirror.usebottles.com`, `dig proxy.usebottles.com` and `ping proxy.usebottles.com`

**Comment by mu-us61** [comment]
```
muhammet@debian:~$ dig mirror.usebottles.com

; <<>> DiG 9.16.33-Debian <<>> mirror.usebottles.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59262
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mirror.usebottles.com.		IN	A

;; ANSWER SECTION:
mirror.usebottles.com.	193	IN	A	194.233.169.173

;; Query time: 44 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan 18 16:32:51 +03 2023
;; MSG SIZE  rcvd: 66

muhammet@debian:~$ ping mirror.usebottles.com
PING mirror.usebottles.com (194.233.169.173) 56(84) bytes of data.
64 bytes from Bottles-Cloud-FRA-0.usebottles.com (194.233.169.173): icmp_seq=1 ttl=50 time=43.6 ms
64 bytes from Bottles-Cloud-FRA-0.usebottles.com (194.233.169.173): icmp_seq=2 ttl=50 time=43.8 ms
64 bytes from Bottles-Cloud-FRA-0.usebottles.com (194.233.169.173): icmp_seq=3 ttl=50 time=44.1 ms
64 bytes from Bottles-Cloud-FRA-0.usebottles.com (194.233.169.173): icmp_seq=4 ttl=50 time=43.9 ms
64 bytes from Bottles-Cloud-FRA-0.usebottles.com (194.233.169.173): icmp_seq=5 ttl=50 time=44.1 ms
^C
--- mirror.usebottles.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4007ms
rtt min/avg/max/mdev = 43.644/43.919/44.123/0.176 ms
muhammet@debian:~$ dig proxy.usebottles.com

; <<>> DiG 9.16.33-Debian <<>> proxy.usebottles.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54118
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;proxy.usebottles.com.		IN	A

;; ANSWER SECTION:
proxy.usebottles.com.	148	IN	A	172.67.153.15
proxy.usebottles.com.	148	IN	A	104.21.40.150

;; Query time: 44 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan 18 16:33:26 +03 2023
;; MSG SIZE  rcvd: 81

muhammet@debian:~$ ping proxy.usebottles.com
PING proxy.usebottles.com (172.67.153.15) 56(84) bytes of data.
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=1 ttl=56 time=6.10 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=2 ttl=56 time=6.49 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=3 ttl=56 time=6.69 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=4 ttl=56 time=6.22 ms
64 bytes from 172.67.153.15 (172.67.153.15): icmp_seq=5 ttl=56 time=6.32 ms
^C
--- proxy.usebottles.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 6.102/6.364/6.687/0.205 ms
muhammet@debian:~$ 
```

**Comment by francescomasala** [comment]
try to run bottles again, I've changed a couple of things from our side, can you check if it's working?

**Comment by mu-us61** [comment]
![Screenshot_2023-01-18_16-39-52](https://user-images.githubusercontent.com/73366454/213186337-100c2f06-60fb-4156-96e5-a321077cdd3c.png)

**Comment by francescomasala** [comment]
try to open https://proxy.usebottles.com/repo/components/index.yml with a browser

**Comment by mu-us61** [comment]
I can download the file it starts with : 
```
# -----------------------
# DO NOT EDIT !!!
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY
# DO YOUR MODIFICATION IN THE 'input_files' DIRECTORY INSTEAD
# -----------------------

# ./input_files/1-runtime.yml
# -----------------------
runtime-0.6:
  Category: runtimes
  Channel: stable

runtime-0.5:
  Category: runtimes
  Channel: stable

# ./input_files/2-winebridge.yml
# -----------------------
winebridge-1.1.0:
  Category: winebridge
  Channel: stable
```
