### ISSUE TITLE
[Request]: Option to sort library

### ISSUE THREAD

**Issue by ElbertCode** [bottlesdevs/Bottles#2822]
### Tell us the problem or your need

Currently every new app added to the library is always on the top.

### Describe the solution you'd like

Add an option to list the apps in the library in ascending and descending order and by additional values such as name, date last used, etc. If Issue #1273 is going to be implemented, it could also be sorted by play time.

### Other solutions?

Alternatively, items in the library could be arranged completely freely.

**Comment by Froggy232** [comment]
Hi,
I strongly agree with your opinion, there should really be an option to sort alphabetically.
Actually, it's nearly impossible to navigate in an important library without the search function.
Thanks to the devs for their work.

**Comment by Carlos-von-Esteban-98** [comment]
Agreed, just look at this mess. 

<img src="https://i.imgur.com/GMefI6M.png"/>

To add to your original comment, maybe there should also be a way to make thumbnails smaller. 
I dont know about you, but my screen can only fit five in each row, and that's too little.(the image above has been reduced in size in  order to load faster.)

**Comment by Carlos-von-Esteban-98** [comment]
> Currently every new app added to the library is always on the top.

No, not really, they are sorted by their "ids"(idk what to call them) that are in ~/.var/app/com.usebottles.bottles/data/bottles/library.yml

for example:
```
05519fae-d638-46bd-8635-fb419ef30cbc:
  bottle:
    name: win7x64
    path: win7x64
  icon: "/home/wine_user/.var/app/com.usebottles.bottles/data/bottles/bottles/win7x64/icons/Grand
    Theft Auto\u2122 \uFB06 Andreas.png"
  id: 27be9786-5216-485a-a247-3a323792f190
  name: "Grand Theft Auto\u2122 San Andreas"
  thumbnail: grid:92254af6-9106-4d6b-abea-d9d1ff7750a8.png
05fcb106-bdba-488f-b855-f8b37e51e0e3:
  bottle:
    name: test7
    path: test7
  icon: "/home/wine_user/.var/app/com.usebottles.bottles/data/bottles/bottles/test7/icons/Need
    for Speed\u2122 Most Wanted.png"
  id: 1b9672f3-8c3b-451b-8efd-ef008ffdfed2
  name: "Need for Speed\u2122 Most Wanted 2005"
  thumbnail: grid:c9e82c0a-24a2-434b-bb62-78be4585f830.jpg
069dacaf-9b5f-4287-a9d3-224da5d7877a:
  bottle:
    name: WinXP-32
    path: WinXP-32
  icon: /home/wine_user/.var/app/com.usebottles.bottles/data/bottles/bottles/WinXP-32/icons/Bejeweled
    2.png
  id: e0b9c084-78af-4630-a4c0-c4ad78eeae91
  name: Bejeweled 2
  thumbnail: grid:3863ccec-aea5-442a-aa27-d23fcb6be68c.png
```

and so on...
Notice how 055.... -> 05f... -> 069...
