### ISSUE TITLE
Library Thumbnails

### ISSUE THREAD

**Issue by Schildkroet** [bottlesdevs/Bottles#2936]
How are thumbnails for the library handled?
For some Bottles it says "No Thumbnail".

How does Bottles select a thumbnail?
How can i assign my own Thumbnail if Bottles doesn't detect it?

![image](https://github.com/bottlesdevs/Bottles/assets/29074960/fa4dbbc6-1cfc-410f-8a07-63cbf702506f)

**Comment by Schildkroet** [comment]
Thanks. This worked

**Comment by norbertkeri** [comment]
This thread comes up in the first few hits on kagi for "add library thumbnails bottles", but the linked forum seems to be down, is there a mirror somewhere?

**Comment by Qronikarz** [comment]
It seems that Internet Archive miraculously archived the guide, which is nice. There were 2 images that didn't make it, but they were just showing the end result so you don't need them.
https://web.archive.org/web/20221207095223/https://forum.usebottles.com/t/guide-custom-cover-arts-in-library-view/673

Though the forum not working yet again should be reported. Really makes you wonder why it has so many connection issues (I reported it myself few times already)

**Comment by Schildkroet** [comment]
@norbertkeri 
**icon** seems to refer to something else.
I have so set **thumbnail**
`thumbnail: grid:pic.png`

**Comment by builtStup1d** [comment]
I found the library.yml but it was empty with just '{}'.

**Comment by Sturmlocke86** [comment]
> @norbertkeri **icon** seems to refer to something else. I have so set **thumbnail** `thumbnail: grid:pic.png`

This worked, thanks! Could a option be added to the interface where we can select a custom thumbnail just by browsing to the image?

**Comment by LukasWillin** [comment]
Since this is what most likely comes up in search engines, I would like to update this thread with some more information regarding the flatpak version of bottles:

I use bottles for my GOG Galaxy Client. Here is how it looks:
![Image](https://github.com/user-attachments/assets/85008f9b-3609-4720-bf27-ce4c811eb42c)

This is my `library.yml`:
`/home/<username>/.var/app/com.usebottles.bottles/data/bottles/library.yml`
```yml
5255d024-c33c-41de-997d-aa4ca7140878:
  bottle:
    name: GOG
    path: GOG
  icon: /home/<username>/.var/app/com.usebottles.bottles/data/bottles/bottles/GOG/icons/GalaxyClient.png
  id: e6709801-0a36-4640-9af5-7a3daff5f66c
  name: GalaxyClient
  thumbnail: grid:gog-galaxy-thumbnail.png
```

This is the referenced cover art:
![Image](https://github.com/user-attachments/assets/49d2dcef-ca94-46bb-86d7-28c2b2054f1d)

If you are looking for the id of your bottle (in my case `e6709801-0a36-4640-9af5-7a3daff5f66c`), you can find it in this file:
`/home/<username>/.var/app/com.usebottles.bottles/data/bottles/bottles/GOG/bottle.yml`:
```yml
Creation_Date: '2023-05-22 12:06:24.283504'
Custom_Path: false
External_Programs:
    e6709801-0a36-4640-9af5-7a3daff5f66c:
        executable: GalaxyClient.exe
        folder: /home/<username>/.var/app/com.usebottles.bottles/data/bottles/bottles/GOG/drive_c/Program
            Files (x86)/GOG Galaxy
        icon: com.usebottles.bottles-program
        id: e6709801-0a36-4640-9af5-7a3daff5f66c
        name: GalaxyClient
        path: C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe
[... a lot of keys removed for brevity]
```

What I cannot tell you is where the first ID is coming from (`5255d024-c33c-41de-997d-aa4ca7140878`). I couldn't find it in any files with grep.
