### ISSUE TITLE
[Request]: Option to automatically update bottles with the latest version of Wine or DLL components

### ISSUE THREAD

**Issue by AlphaJack** [bottlesdevs/Bottles#3247]
### Tell us the problem or your need

Configuring each bottle to use specific versions of runners and components is great as it ensures that each bottle can be run for those versions.

However, there is no way to automatically set bottles to the latest available version of runner/component, as these versions are not dowloaded automatically.

If someone wants to use the latest wine features and free space by deleting old runner versions, he has to download the latest runner version, reconfigure each bottle for each updated component, and delete the old runner version.

This process cannot be automated and takes a lot with a large number of bottles.

### Describe the solution you'd like

1. Add an option to configure bottles to the `latest` available version of runners/components

```yaml
DXVK: dxvk-latest
LatencyFleX: latencyflex-latest
NVAPI: dxvk-nvapi-latest
Runner: wine-ge-proton-latest
VKD3D: vkd3d-proton-latest
```

3. Add an option to automatically download the latest Wine GE/ Proton GE/DLLs when available, so bottles set to `latest` can benefit from the updates.

This should not affect bottles tied to a specific version of the component:

```yaml
DXVK: dxvk-2.2
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6.3
Runner: wine-ge-proton8-13
VKD3D: vkd3d-proton-2.9
```

### Other solutions?

A separate yaml entry, either on a bottle or component basis

```yaml
Auto_Update_Components: true
DXVK: dxvk-2.2
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6.3
Runner: wine-ge-proton8-13
VKD3D: vkd3d-proton-2.9
```

This bottle configuration would be updated as follows:

```yaml
Auto_Update_Components: true
DXVK: dxvk-2.3
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6.4
Runner: wine-ge-proton8-27-lol
VKD3D: vkd3d-proton-2.11.1
```
