### ISSUE TITLE
[Bug]: Bottles stuck on "updating runner and components, please wait"

### ISSUE THREAD

**Issue by james2432** [bottlesdevs/Bottles#3302]
### Describe the bug

I had a bottle that was using sys-wine-8.0-2 but now when launching the new updated bottles, it says the runner is no longer available.

I tried changing the bottles to soda-8.0-2 and it just sits there spinning for over 15 minutes.

### To Reproduce

1. Go to bottle
2.  Update runner to existing one
3. Watch the spinning happen

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.11'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.7.6-arch1-1
Disk:
    Total: 8356511744
    Free: 8356347904
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 11.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
$ flatpak run com.usebottles.bottles
09:22:16 (INFO) Bottles Started! 
09:22:17 (INFO) Performing Bottles checks… 
09:22:17 (INFO) Dxvks found:
	 - dxvk-2.1
 
09:22:17 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8
 
09:22:17 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6.3
 
09:22:17 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
09:22:17 (INFO) Runners found:
	 - soda-8.0-2
	 - wine-ge-proton8-25
	 - sys-wine-9.0
 
09:22:17 (INFO) Bottles found:
	 - LOTRO
 
09:22:18 (INFO) Catalog installers loaded 
09:22:18 (INFO) Catalog dependencies loaded 
09:22:18 (INFO) Catalog components loaded 
09:22:21 (INFO) Setting Key sync=fsync for bottle LOTRO… 
09:22:21 (INFO) There is no running wineserver. 
09:22:31 (INFO) Doing runner update for bottle: LOTRO 
09:22:32 (INFO) Using Wine Runtime tool -- send_status(-k)
```

**Comment by james2432** [comment]
The only way I found to fix it is to create a new bottle and start from scratch. Seems the upgrade path is lacking a bit when the wine version is changed

**Comment by mirkobrombin** [comment]
Try editing the runner from the configuration file instead, let me know. The path is `~/.var/app/com.usebottles.bottles/data/bottles/bottles/<your_bottles>`.

**Comment by james2432** [comment]
what exactly am I looking for in the bottle?
I see 

- bottle.yml
- cache
- dosdevices
- drive_c
- system.reg
- template.yml
- userdef.reg
- user reg

**Comment by mirkobrombin** [comment]
bottle.yml

**Comment by james2432** [comment]
[patchfile.txt](https://github.com/bottlesdevs/Bottles/files/15114905/patchfile.txt)
This is the difference between the working one and the non-working original one

**Comment by mirkobrombin** [comment]
For instance, this is how a clean gaming bottle appear:

```yaml
Arch: win64
CompatData: ''
Creation_Date: '2024-04-25 18:17:40.311811'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.3.1
Environment: Gaming
Environment_Variables: {}
External_Programs:
    cf1dbdfc-5bd1-4db8-b049-968078da34ad:
        arguments: ''
        executable: UbisoftConnect.exe
        id: cf1dbdfc-5bd1-4db8-b049-968078da34ad
        name: Ubisoft Connect
        path: C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\UbisoftConnect.exe
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- gecko
- riched20
- andale32
- arialb32
- comic32
- georgi32
- impact32
- tahoma32
- trebuc32
- verdan32
- webdin32
- allfonts
- vcredist2015
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.7.0
Name: Games
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: Games
Runner: ge-proton9-4
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2024-04-25 18:27:49.278300'
VKD3D: vkd3d-proton-2.12
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
```
