### ISSUE TITLE
[Request]: Add an option for installers to set HTTP headers when downloading a file.

### ISSUE THREAD

**Issue by CaitlynWemyss** [bottlesdevs/Bottles#3722]
### Tell us the problem or your need

Some servers are stubborn, and will not allow files to be downloaded unless certain headers are included in the HTTP request. This would make it (maybe) possible to fix bottlesdevs/programs#337.

### Describe the solution you'd like

The Steps item in the YAML could include an "http_headers" item, like so:

```yaml
Steps:
- action: install_exe
  file_name: flstudio_win64_24.1.1.4239.exe
  url: https://install.image-line.com/flstudio/flstudio_win64_24.1.1.4239.exe
  http_headers:
  - "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0"
  - "Accept-Language": "en-US,en;q=0.5"
  file_checksum: b96beab4069b9ce9137ca133fab5fff5
  arguments: ""
```
