### ISSUE TITLE
[Request] Installers update_config aciton to interact with config files

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/Bottles#942]
Some programs came with their configuration files, which should be tweaked to make it run at its best.

Example:
- epicgamestore notifications are very buggy and should be disabled, also the default close behavior should be switched from minimized to just close
- overwatch video encoding should be changed to webm, otherwise will not works

New `update_config` example:
```yaml
- action: update_config
  path: drive_c/.../config.yml
  type: yml
  upd_keys: 
    key1: Test
    key2:
      key3: test
    key4: test
  del_keys:
    - [key3, subKey1]
    - [key6, subKey4, subSubKey1]
```
