### ISSUE TITLE
[Bug / Half Solved] Wine configruation can't be created on AUR executable

### ISSUE THREAD

**Issue by qogusdn1017** [bottlesdevs/Bottles#992]
**Describe the situation**
As mentioned in the issue title & contents earlier it's taking so long it never ends.

**Installation**
 - Method: yay
 - Version: 2022.1.28-trento

**To Reproduce**
1. Create a new bottle.
2. This happens...

**Expected behavior**
Wine configuration has to be successfully created.

**Screenshots**

![ok so when](https://user-images.githubusercontent.com/36562850/151703720-5dabb2b9-da7b-4dea-bcee-6a2ddc68d10e.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x64
 - Version: 2022.01.01, Kernel Version: 5.15.12
 - Display server: Xorg (KDE)

**Additional context**

i7-12700KF / RX 6600XT.

Currently, I can create a Wine Config using the `winecfg` command.

It would be nice if you could manual "Create a Wine Config" function or create a timeout for Wine Config creation time :)

**Comment by mirkobrombin** [comment]
We use a wrapper to wineboot that initialize the new prefix:

https://github.com/bottlesdevs/Bottles/blob/8bd2a66dd6b1d69ae6e33cb3f2cef4c3dd4bb2ee/src/backend/manager.py#L1110

should not take so much. I'll investigate. Can you test with flatpak to exclude an "external" problem?

**Comment by qogusdn1017** [comment]
Using fresh flatpack, fresh bottles. UI seems to be fixed and it's beautiful.

Unfortunately, issue not resolved. Wine stuck at creating configuration.

**Comment by mirkobrombin** [comment]
This makes no sense, I’m setting up a vm to test

**Comment by qogusdn1017** [comment]
It might be my issue since it's working on AMD Ryzen 3 2200G.

After turning into i7-12700 it seems not working; don't know if this is related to the wine.

**Comment by mirkobrombin** [comment]
I don't think..  Can you check if there are files in the new bottle directory?

**Comment by qogusdn1017** [comment]
It does create directories and files.

After restarting and running Bottles to create a new bottle and...
![okay wtf](https://user-images.githubusercontent.com/36562850/151761392-0a6e043b-9912-4f04-a777-48bf39ffc0d5.png)

Yea it created the bottle! But it seems like something is wrong with the gstreamer I think. I haven't gotten these warning messages before.

**Comment by qogusdn1017** [comment]
Differences with the Flatpak/AUR are just with the bottle creation. It can/can't create a bottle.

**Comment by mirkobrombin** [comment]
Ya these are just warnings and ca be safely ignored. Can you share the bottle.yml?

**Comment by qogusdn1017** [comment]
All bottle functions are now working. Here is bottle.yml:

```yml
Arch: win32
Creation_Date: '2022-01-31 17:27:22.203364'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.4
Environment: Custom
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- allfonts
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.1
Name: KakaoTalk
Parameters:
    aco_compiler: false
    discrete_gpu: false
    dxvk: false
    dxvk_hud: false
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    pulseaudio_latency: false
    sync: wine
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: false
Path: KakaoTalk
Runner: lutris-5.21-2
State: 0
Uninstallers:
    allfonts: false
Update_Date: '2022-01-31 17:38:23.370497'
VKD3D: vkd3d-proton-2.5
Versioning: false
Windows: win10
WorkingDir: ''
```
